druid:
  initialSize: 5
  minIdle: 10
  maxActive: 300
  maxWait: 60000
  timeBetweenEvictionRunsMills: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPerparedStatements: false
  maxPoolPreparedStatementPerConnectionSize: 2
  filters: stat,wall,logback
  useGlobalDataSourceStat: true

